### ISSUE TITLE
no buildable Go source

### ISSUE THREAD

**Issue by DimShadoWWW** [flimzy/go-pouchdb#25]
Hello, I'm using go 1.5.3 and with "go get github.com/flimzy/go-pouchdb" I'm getting this error:

```
can't load package: package github.com/flimzy/go-pouchdb: no buildable Go source files in /go/src/github.com/flimzy/go-pouchdb
```

**Comment by flimzy** [comment]
This is because there is no "Go" code in the package, only GopherJS code. The important distinction being the build flag [at the top of the source files](https://github.com/flimzy/go-pouchdb/blob/master/pouchdb.go#L1):

> // +build js

However, the package is still installed with the command you issued, and should be usable for your GopherJS projects.

The error message is unfortunate, as it indicates an error condition that doesn't really matter in this case. And adding the `-d` flag to the command doesn't avoid the error (even though it seems to me it should).

Beyond that, is there any specific problem you're having? Are you able to use go-pouchdb in your GopherJS programs once its installed?

**Comment by DimShadoWWW** [comment]
Yes, gopherjs can't find module pouchdb.. this is an example:

``` Go
package main

import (
    "time"

    "github.com/flimzy/go-pouchdb"
    "github.com/gopherjs/gopherjs/js"
)

var (
    ldb = pouchdb.New("test-deck")
)

func main() {
    js.Global.Set("Task", map[string]interface{}{
        "New": New,
    })
}

// Task struct
type Task struct {
    task    string
    status  string
    created time.Time
    edited  time.Time
}

// New : Create task
func New(task string) *js.Object {
    return js.MakeWrapper(&Task{
        task:    task,
        status:  "new",
        created: time.Now(),
        edited:  time.Now(),
    })
}
```

when I run this example using: gopherjs run app.go , I get this error:

```
gopherjs: Source maps disabled. Use Node.js 4.x with source-map-support module for nice stack traces.
/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:1472
        throw err;
        ^

Error: Cannot find module 'pouchdb'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at $packages.github.com/flimzy/go-pouchdb.globalPouch (//home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:24265:26)
    at Object.$packages.github.com/flimzy/go-pouchdb.New (/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:24271:31)
    at $packages.main.$init (/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:24747:17)
    at $goroutine (/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:1463:19)
    at $schedule (/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:1520:5)
    at $go (/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:1496:3)
    at Object.<anonymous> (/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:24760:1)
    at Object.<anonymous> (/home/user/go/src/github.com/USER/tasksmanager/app.go.349514829:24763:4)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by flimzy** [comment]
Ah!  That's an entirely different error, coming from node, not from GopherJS. It means it can't find the node module, 'pouchdb'. You will need to install the pouchdb module with npm:

```
npm install pouchdb
```

Or you can create a `package.json` file with your Nodejs requirement(s):

```
{
  "name": "app",
  "version": "1.0.0",
  "dependencies": {
      "pouchdb": ">=4.0.2"
  }
}
```

Then run `npm install`.

For deployment, you'll either need to bundle your JS together with something like browserify (my preferred method), or arrange to load pouchdb before your GopherJS output:

```
<html><head>
    <script src="path/to/pouchdb.js"></script>
    <script src="path/to/app.js"></script>
</head>...
```

I'll be sure to add this to the README for future reference.

**Comment by flimzy** [comment]
I have updated the README.  Please let me know how I might be able to clarify further.
